# Generated by Django 2.2.15 on 2020-08-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200811_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='alias',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='lastname',
        ),
    ]
